### ISSUE TITLE
Just a tiny correction for solidity.tmLanguage.json

### ISSUE THREAD

**Issue by AntonKordes** [tintinweb/vscode-solidity-language#1]
https://github.com/tintinweb/vscode-solidity-language/blob/f4cc41db4a563e9fc56594834c10844dab25dcfb/src/syntaxes/solidity.tmLanguage.json#L285

Should be:
`            "match": "\\b([A-Z_][A-Z0-9_]+)\\b",`

**Comment by tintinweb** [comment]
Thanks @AntonKordes 🙌
